### ISSUE TITLE
NSCA-crash

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/mod-nsca#7]
```
c:\Program Files\NSClient++>cscript.exe //T:30 //NoLogo scripts\lib\wrapper.vbs scripts\check_updates.vbs -warning 0 -critical 0
OK: Number of critical updates not installed: 3 <br />Number of software updates not installed: 0 <br /> Critical updates name: 2017-08 Kumulatives Update für Windows 10 Version 1703 für x64-basierte Systeme (KB4034674)+ Windows-Tool zum Entfernen bösartiger Software für Windows 8, 8.1, 10 und Windows Server 2012, 2012 R2, 2016 x64 Edition - August 2017 (KB890830)+ 2017-08 Sicherheitsupdate für Adobe Flash Player für Windows 10 Version 1703 für x64-basierte Systeme (KB4034662)+
```

```
[2017-08-09 23:38:20 CEST] INFO: [alignak.module.nsca] Decoded NSCA packet: host/service: test-b/nsca_updates, timestamp: 1502314700, output: OK: Number of critical updates not installed: 3 <br />Number of software updates not installed: 0 <br /> Critical
updates name: 2017-08 Kumulatives Update f.r Windows 10 Version 1703 f.r x64-basierte Systeme (KB4034674)+ Windows-Tool zum Entfernen b”sartig
[2017-08-09 23:38:20 CEST] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2017-08-09 23:38:20 CEST] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-08-09 23:38:20 CEST] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as
 possible (version, configuration, ...
[2017-08-09 23:38:20 CEST] CRITICAL: [alignak.daemon] -----
[2017-08-09 23:38:20 CEST] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/receiverdaemon.py", line 461, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 408, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/receiverdaemon.py", line 425, in do_loop_turn
    self.push_external_commands_to_schedulers()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/receiverdaemon.py", line 385, in push_external_commands_to_schedul
ers
    "sending external commands: %s", sched.scheduler_name, str(exp))
AttributeError: 'dict' object has no attribute 'scheduler_name'

[2017-08-09 23:38:21 CEST] INFO: [alignak.basemodule] Process for module web-services is now exiting (pid=24529)
```

```
----------------------------------------------------
 ----  TCP         127.0.0.1  5667 NSCA
 ----  TCP         127.0.0.1  8888 WServices
----------------------------------------------------
       # /usr/local/etc/alignak-backend/uwsgi.ini
 open  TCP         127.0.0.1  5000 uwsgi.ini
----------------------------------------------------
       # /usr/local/etc/alignak-webui/uwsgi.ini
 open  TCP         127.0.0.1  5001 uwsgi.ini
----------------------------------------------------
       # /usr/local/etc/alignak/daemons
 open  TCP         127.0.0.1  7773 receiverd.ini
 open  TCP         127.0.0.1  7772 brokerd.ini
 open  TCP         127.0.0.1  7770 arbiterd.ini
 open  TCP         127.0.0.1  7768 schedulerd.ini
 open  TCP         127.0.0.1  7769 reactionnerd.ini
 open  TCP         127.0.0.1  7771 pollerd.ini
----------------------------------------------------
       # /usr/local/etc/alignak/arbiter/daemons
 open  TCP         127.0.0.1  7771 poller-master.cfg
 open  TCP         127.0.0.1  7768 scheduler-master.cfg
 open  TCP         127.0.0.1  7769 reactionner-master.cfg
 open  TCP         127.0.0.1  7772 broker-master.cfg
 open  TCP         127.0.0.1  7770 arbiter-master.cfg
 open  TCP         127.0.0.1  7773 receiver-master.cfg

```

**Comment by mohierf** [comment]
This is not an issue for the NSCA module, but an issue of Alignak framework, related to https://github.com/Alignak-monitoring/alignak/issues/887

**Comment by mohierf** [comment]
Fixed in Alignak
